# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1051, 746)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(40, 650, 341, 23))
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.fileLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.fileLabel.setGeometry(QtCore.QRect(40, 400, 341, 24))
        self.fileLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.fileLabel.setObjectName("fileLabel")
        self.fileButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.fileButton.setGeometry(QtCore.QRect(40, 440, 75, 24))
        self.fileButton.setStyleSheet("background-color: rgb(94, 94, 94);\n"
"color: rgb(255, 255, 255);")
        self.fileButton.setObjectName("fileButton")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(580, 30, 441, 651))
        self.scrollArea.setStyleSheet("background-color: rgb(94, 94, 94);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 649))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 70, 157, 26))
        self.widget.setObjectName("widget")
        self.userIPHBox = QtWidgets.QHBoxLayout(self.widget)
        self.userIPHBox.setContentsMargins(0, 0, 0, 0)
        self.userIPHBox.setSpacing(40)
        self.userIPHBox.setObjectName("userIPHBox")
        self.ipLabel = QtWidgets.QLabel(parent=self.widget)
        self.ipLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipLabel.setObjectName("ipLabel")
        self.userIPHBox.addWidget(self.ipLabel)
        self.copyButton = QtWidgets.QPushButton(parent=self.widget)
        self.copyButton.setStyleSheet("background-color: rgb(94, 94, 94);\n"
"color: rgb(255, 255, 255);")
        self.copyButton.setObjectName("copyButton")
        self.userIPHBox.addWidget(self.copyButton)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 190, 257, 51))
        self.widget1.setObjectName("widget1")
        self.receiverIPVBox = QtWidgets.QVBoxLayout(self.widget1)
        self.receiverIPVBox.setContentsMargins(0, 0, 0, 0)
        self.receiverIPVBox.setObjectName("receiverIPVBox")
        self.ipSendLabel = QtWidgets.QLabel(parent=self.widget1)
        self.ipSendLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"padding-left: 45px;")
        self.ipSendLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ipSendLabel.setObjectName("ipSendLabel")
        self.receiverIPVBox.addWidget(self.ipSendLabel)
        self.receiverIPHBox = QtWidgets.QHBoxLayout()
        self.receiverIPHBox.setObjectName("receiverIPHBox")
        self.ipLine = QtWidgets.QLineEdit(parent=self.widget1)
        self.ipLine.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipLine.setObjectName("ipLine")
        self.receiverIPHBox.addWidget(self.ipLine)
        self.ipConfirmButton = QtWidgets.QPushButton(parent=self.widget1)
        self.ipConfirmButton.setStyleSheet("background-color: rgb(94, 94, 94);\n"
"color: rgb(255, 255, 255);")
        self.ipConfirmButton.setObjectName("ipConfirmButton")
        self.receiverIPHBox.addWidget(self.ipConfirmButton)
        self.receiverIPVBox.addLayout(self.receiverIPHBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1051, 22))
        self.menubar.setStyleSheet("")
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setStyleSheet("background-color: rgb(59, 59, 59);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fileLabel.setText(_translate("MainWindow", "Chosen file:"))
        self.fileButton.setText(_translate("MainWindow", "Choose File"))
        self.ipLabel.setText(_translate("MainWindow", "Your IP:"))
        self.copyButton.setText(_translate("MainWindow", "Copy"))
        self.ipSendLabel.setText(_translate("MainWindow", "Send to ip"))
        self.ipLine.setText(_translate("MainWindow", "Send to IP"))
        self.ipConfirmButton.setText(_translate("MainWindow", "Confirm"))
