# Form implementation generated from reading ui file './ui/gui_layout.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 790)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(34,35,37)")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        spacerItem = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_68.addItem(spacerItem)
        self.ipLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipLabel.sizePolicy().hasHeightForWidth())
        self.ipLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.ipLabel.setFont(font)
        self.ipLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipLabel.setObjectName("ipLabel")
        self.horizontalLayout_68.addWidget(self.ipLabel)
        self.verticalLayout_25.addLayout(self.horizontalLayout_68)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.copyButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyButton.sizePolicy().hasHeightForWidth())
        self.copyButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setBold(True)
        self.copyButton.setFont(font)
        self.copyButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2); \n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9); \n"
"}")
        self.copyButton.setObjectName("copyButton")
        self.horizontalLayout_69.addWidget(self.copyButton)
        spacerItem1 = QtWidgets.QSpacerItem(12, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem1)
        self.usePortLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usePortLabel.sizePolicy().hasHeightForWidth())
        self.usePortLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.usePortLabel.setFont(font)
        self.usePortLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.usePortLabel.setObjectName("usePortLabel")
        self.horizontalLayout_69.addWidget(self.usePortLabel)
        self.portSpinBox = QtWidgets.QSpinBox(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portSpinBox.sizePolicy().hasHeightForWidth())
        self.portSpinBox.setSizePolicy(sizePolicy)
        self.portSpinBox.setMinimumSize(QtCore.QSize(98, 0))
        self.portSpinBox.setStyleSheet("QSpinBox {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 7px;\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setProperty("value", 0)
        self.portSpinBox.setObjectName("portSpinBox")
        self.horizontalLayout_69.addWidget(self.portSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem2)
        self.verticalLayout_25.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_70 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_70.setObjectName("horizontalLayout_70")
        self.enableReceivingButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableReceivingButton.sizePolicy().hasHeightForWidth())
        self.enableReceivingButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.enableReceivingButton.setFont(font)
        self.enableReceivingButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9); \n"
"}")
        self.enableReceivingButton.setObjectName("enableReceivingButton")
        self.horizontalLayout_70.addWidget(self.enableReceivingButton)
        self.disableReceivingButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disableReceivingButton.sizePolicy().hasHeightForWidth())
        self.disableReceivingButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.disableReceivingButton.setFont(font)
        self.disableReceivingButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.disableReceivingButton.setObjectName("disableReceivingButton")
        self.horizontalLayout_70.addWidget(self.disableReceivingButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_70.addItem(spacerItem3)
        self.verticalLayout_25.addLayout(self.horizontalLayout_70)
        self.horizontalLayout_67.addLayout(self.verticalLayout_25)
        self.verticalLayout_29.addLayout(self.horizontalLayout_67)
        self.line_13 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_13.setStyleSheet("")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setLineWidth(2)
        self.line_13.setMidLineWidth(0)
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_29.addWidget(self.line_13)
        spacerItem4 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem4)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        spacerItem5 = QtWidgets.QSpacerItem(8, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem5)
        self.ipSendLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipSendLabel.sizePolicy().hasHeightForWidth())
        self.ipSendLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.ipSendLabel.setFont(font)
        self.ipSendLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipSendLabel.setObjectName("ipSendLabel")
        self.horizontalLayout_64.addWidget(self.ipSendLabel)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_64.addItem(spacerItem6)
        self.verticalLayout_24.addLayout(self.horizontalLayout_64)
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.ipLine = QtWidgets.QLineEdit(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipLine.sizePolicy().hasHeightForWidth())
        self.ipLine.setSizePolicy(sizePolicy)
        self.ipLine.setMinimumSize(QtCore.QSize(185, 0))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.ipLine.setFont(font)
        self.ipLine.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #4d4d4d;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    color: white;\n"
"}")
        self.ipLine.setPlaceholderText("")
        self.ipLine.setObjectName("ipLine")
        self.horizontalLayout_65.addWidget(self.ipLine)
        self.connectingSpinnerLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectingSpinnerLabel.sizePolicy().hasHeightForWidth())
        self.connectingSpinnerLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.connectingSpinnerLabel.setFont(font)
        self.connectingSpinnerLabel.setStyleSheet("")
        self.connectingSpinnerLabel.setText("")
        self.connectingSpinnerLabel.setScaledContents(True)
        self.connectingSpinnerLabel.setObjectName("connectingSpinnerLabel")
        self.horizontalLayout_65.addWidget(self.connectingSpinnerLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem7)
        self.verticalLayout_24.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.connectButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.connectButton.setFont(font)
        self.connectButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_66.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.disconnectButton.setFont(font)
        self.disconnectButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout_66.addWidget(self.disconnectButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem8)
        self.verticalLayout_24.addLayout(self.horizontalLayout_66)
        self.verticalLayout_29.addLayout(self.verticalLayout_24)
        spacerItem9 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem9)
        self.line_11 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_11.setLineWidth(2)
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_29.addWidget(self.line_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem10)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        spacerItem11 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem11)
        self.chosenFileLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chosenFileLabel.sizePolicy().hasHeightForWidth())
        self.chosenFileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.chosenFileLabel.setFont(font)
        self.chosenFileLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.chosenFileLabel.setObjectName("chosenFileLabel")
        self.horizontalLayout_74.addWidget(self.chosenFileLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem12)
        self.verticalLayout_28.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.chooseFileButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseFileButton.sizePolicy().hasHeightForWidth())
        self.chooseFileButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.chooseFileButton.setFont(font)
        self.chooseFileButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.chooseFileButton.setObjectName("chooseFileButton")
        self.horizontalLayout_75.addWidget(self.chooseFileButton)
        self.sendButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.sendButton.setFont(font)
        self.sendButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_75.addWidget(self.sendButton)
        self.fileSentLabel = QtWidgets.QLabel(parent=self.mainPage)
        self.fileSentLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSentLabel.sizePolicy().hasHeightForWidth())
        self.fileSentLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.fileSentLabel.setFont(font)
        self.fileSentLabel.setStyleSheet("color: #4CAF50;")
        self.fileSentLabel.setObjectName("fileSentLabel")
        self.horizontalLayout_75.addWidget(self.fileSentLabel)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem13)
        self.verticalLayout_28.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.sendProgressBar = QtWidgets.QProgressBar(parent=self.mainPage)
        self.sendProgressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendProgressBar.sizePolicy().hasHeightForWidth())
        self.sendProgressBar.setSizePolicy(sizePolicy)
        self.sendProgressBar.setMinimumSize(QtCore.QSize(190, 0))
        self.sendProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.sendProgressBar.setFont(font)
        self.sendProgressBar.setStyleSheet("QProgressBar {\n"
"    border-radius: 5px;\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    text-align: center;\n"
"    color: white\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    /* Progress Version */\n"
"    background-color: #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.sendProgressBar.setProperty("value", 0)
        self.sendProgressBar.setTextVisible(True)
        self.sendProgressBar.setInvertedAppearance(False)
        self.sendProgressBar.setObjectName("sendProgressBar")
        self.horizontalLayout_76.addWidget(self.sendProgressBar)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem14)
        self.verticalLayout_28.addLayout(self.horizontalLayout_76)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.receiverDownloadedFileLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiverDownloadedFileLabel.sizePolicy().hasHeightForWidth())
        self.receiverDownloadedFileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.receiverDownloadedFileLabel.setFont(font)
        self.receiverDownloadedFileLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.receiverDownloadedFileLabel.setObjectName("receiverDownloadedFileLabel")
        self.horizontalLayout_77.addWidget(self.receiverDownloadedFileLabel)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem15)
        self.verticalLayout_28.addLayout(self.horizontalLayout_77)
        self.verticalLayout_29.addLayout(self.verticalLayout_28)
        spacerItem16 = QtWidgets.QSpacerItem(20, 22, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem16)
        self.line_12 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_12.setLineWidth(2)
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_29.addWidget(self.line_12)
        spacerItem17 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem17)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        spacerItem18 = QtWidgets.QSpacerItem(3, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem18)
        self.readyToReceiveLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readyToReceiveLabel.sizePolicy().hasHeightForWidth())
        self.readyToReceiveLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.readyToReceiveLabel.setFont(font)
        self.readyToReceiveLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.readyToReceiveLabel.setObjectName("readyToReceiveLabel")
        self.horizontalLayout_71.addWidget(self.readyToReceiveLabel)
        self.verticalLayout_27.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.receiveButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveButton.sizePolicy().hasHeightForWidth())
        self.receiveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.receiveButton.setFont(font)
        self.receiveButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.receiveButton.setObjectName("receiveButton")
        self.horizontalLayout_72.addWidget(self.receiveButton)
        self.rejectButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rejectButton.sizePolicy().hasHeightForWidth())
        self.rejectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.rejectButton.setFont(font)
        self.rejectButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout_72.addWidget(self.rejectButton)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_72.addItem(spacerItem19)
        self.verticalLayout_27.addLayout(self.horizontalLayout_72)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setSpacing(6)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.receiveProgressBar = QtWidgets.QProgressBar(parent=self.mainPage)
        self.receiveProgressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveProgressBar.sizePolicy().hasHeightForWidth())
        self.receiveProgressBar.setSizePolicy(sizePolicy)
        self.receiveProgressBar.setMinimumSize(QtCore.QSize(190, 0))
        self.receiveProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.receiveProgressBar.setFont(font)
        self.receiveProgressBar.setStyleSheet("QProgressBar {\n"
"    border-radius: 5px;\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    text-align: center;\n"
"    color: white\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    /* Progress Version */\n"
"    background-color: #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.receiveProgressBar.setProperty("value", 0)
        self.receiveProgressBar.setTextVisible(True)
        self.receiveProgressBar.setInvertedAppearance(False)
        self.receiveProgressBar.setObjectName("receiveProgressBar")
        self.horizontalLayout_73.addWidget(self.receiveProgressBar)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_73.addItem(spacerItem20)
        self.verticalLayout_27.addLayout(self.horizontalLayout_73)
        self.verticalLayout_29.addLayout(self.verticalLayout_27)
        spacerItem21 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem21)
        self.line_10 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_10.setLineWidth(2)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_29.addWidget(self.line_10)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.receivingLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivingLabel.sizePolicy().hasHeightForWidth())
        self.receivingLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(9)
        font.setBold(True)
        self.receivingLabel.setFont(font)
        self.receivingLabel.setStyleSheet("color: red;")
        self.receivingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.receivingLabel.setObjectName("receivingLabel")
        self.verticalLayout_26.addWidget(self.receivingLabel)
        self.inboundConnectionLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inboundConnectionLabel.sizePolicy().hasHeightForWidth())
        self.inboundConnectionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(9)
        font.setBold(True)
        self.inboundConnectionLabel.setFont(font)
        self.inboundConnectionLabel.setStyleSheet("color: red;")
        self.inboundConnectionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.inboundConnectionLabel.setObjectName("inboundConnectionLabel")
        self.verticalLayout_26.addWidget(self.inboundConnectionLabel)
        self.outboundConnectionLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outboundConnectionLabel.sizePolicy().hasHeightForWidth())
        self.outboundConnectionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setBold(True)
        self.outboundConnectionLabel.setFont(font)
        self.outboundConnectionLabel.setStyleSheet("color: red;")
        self.outboundConnectionLabel.setObjectName("outboundConnectionLabel")
        self.verticalLayout_26.addWidget(self.outboundConnectionLabel)
        self.verticalLayout_29.addLayout(self.verticalLayout_26)
        self.stackedWidget.addWidget(self.mainPage)
        self.loadingPage = QtWidgets.QWidget()
        self.loadingPage.setObjectName("loadingPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.loadingPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem22)
        self.loadingSpinnerLabel = QtWidgets.QLabel(parent=self.loadingPage)
        self.loadingSpinnerLabel.setText("")
        self.loadingSpinnerLabel.setObjectName("loadingSpinnerLabel")
        self.verticalLayout_4.addWidget(self.loadingSpinnerLabel)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem23)
        self.stackedWidget.addWidget(self.loadingPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setBold(True)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "P2P File Share"))
        self.ipLabel.setText(_translate("MainWindow", "Your IP:"))
        self.copyButton.setText(_translate("MainWindow", "Copy IP + Port"))
        self.usePortLabel.setText(_translate("MainWindow", "Port:"))
        self.enableReceivingButton.setText(_translate("MainWindow", "Enable Receiving"))
        self.disableReceivingButton.setText(_translate("MainWindow", "Disable Receiving"))
        self.ipSendLabel.setText(_translate("MainWindow", "Connect to IP and port"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.chosenFileLabel.setText(_translate("MainWindow", "Chosen file:"))
        self.chooseFileButton.setText(_translate("MainWindow", "Choose File"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.fileSentLabel.setText(_translate("MainWindow", "File sent"))
        self.receiverDownloadedFileLabel.setText(_translate("MainWindow", "The sent file has not yet been downloaded by the receiver"))
        self.readyToReceiveLabel.setText(_translate("MainWindow", "Ready to receive:"))
        self.receiveButton.setText(_translate("MainWindow", "Receive"))
        self.rejectButton.setText(_translate("MainWindow", "Reject"))
        self.receivingLabel.setText(_translate("MainWindow", "Receiving disabled"))
        self.inboundConnectionLabel.setText(_translate("MainWindow", "No inbound connection"))
        self.outboundConnectionLabel.setText(_translate("MainWindow", "No outbound connection"))
