# Form implementation generated from reading ui file 'src/ui/gui_layout.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 806)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(34,35,37)")
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setObjectName("mainPage")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.mainPage)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.ipLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ipLabel.sizePolicy().hasHeightForWidth())
        self.ipLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        self.ipLabel.setFont(font)
        self.ipLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.ipLabel.setObjectName("ipLabel")
        self.horizontalLayout_68.addWidget(self.ipLabel)
        self.verticalLayout_25.addLayout(self.horizontalLayout_68)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fingerprintLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fingerprintLabel.sizePolicy().hasHeightForWidth())
        self.fingerprintLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.fingerprintLabel.setFont(font)
        self.fingerprintLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.fingerprintLabel.setObjectName("fingerprintLabel")
        self.horizontalLayout.addWidget(self.fingerprintLabel)
        self.verticalLayout_25.addLayout(self.horizontalLayout)
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.copyIPButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyIPButton.sizePolicy().hasHeightForWidth())
        self.copyIPButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        self.copyIPButton.setFont(font)
        self.copyIPButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2); \n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9); \n"
"}")
        self.copyIPButton.setObjectName("copyIPButton")
        self.horizontalLayout_69.addWidget(self.copyIPButton)
        self.copyFingerprintButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyFingerprintButton.sizePolicy().hasHeightForWidth())
        self.copyFingerprintButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.copyFingerprintButton.setFont(font)
        self.copyFingerprintButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2); \n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9); \n"
"}")
        self.copyFingerprintButton.setObjectName("copyFingerprintButton")
        self.horizontalLayout_69.addWidget(self.copyFingerprintButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem)
        self.verticalLayout_25.addLayout(self.horizontalLayout_69)
        self.horizontalLayout_67.addLayout(self.verticalLayout_25)
        self.verticalLayout_29.addLayout(self.horizontalLayout_67)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem1)
        self.line_13 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_13.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.line_13.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_13.setLineWidth(1)
        self.line_13.setMidLineWidth(0)
        self.line_13.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_13.setObjectName("line_13")
        self.verticalLayout_29.addWidget(self.line_13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.usePortLabel = QtWidgets.QLabel(parent=self.mainPage)
        font = QtGui.QFont()
        font.setBold(True)
        self.usePortLabel.setFont(font)
        self.usePortLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.usePortLabel.setObjectName("usePortLabel")
        self.horizontalLayout_2.addWidget(self.usePortLabel)
        self.portSpinBox = QtWidgets.QSpinBox(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portSpinBox.sizePolicy().hasHeightForWidth())
        self.portSpinBox.setSizePolicy(sizePolicy)
        self.portSpinBox.setMinimumSize(QtCore.QSize(98, 0))
        self.portSpinBox.setMaximumSize(QtCore.QSize(16777215, 28))
        self.portSpinBox.setStyleSheet("QSpinBox {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border: 1px solid #4d4d4d;\n"
"    border-radius: 7px;\n"
"    padding-left: 2px;\n"
"    padding-right: 2px;\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setObjectName("portSpinBox")
        self.horizontalLayout_2.addWidget(self.portSpinBox)
        self.enableReceivingButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enableReceivingButton.sizePolicy().hasHeightForWidth())
        self.enableReceivingButton.setSizePolicy(sizePolicy)
        self.enableReceivingButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7); \n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9); \n"
"}")
        self.enableReceivingButton.setObjectName("enableReceivingButton")
        self.horizontalLayout_2.addWidget(self.enableReceivingButton)
        self.disableReceivingButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disableReceivingButton.sizePolicy().hasHeightForWidth())
        self.disableReceivingButton.setSizePolicy(sizePolicy)
        self.disableReceivingButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.disableReceivingButton.setObjectName("disableReceivingButton")
        self.horizontalLayout_2.addWidget(self.disableReceivingButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_29.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(parent=self.mainPage)
        self.line.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_29.addWidget(self.line)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.incomingConnectionLabel = QtWidgets.QLabel(parent=self.mainPage)
        font = QtGui.QFont()
        font.setBold(True)
        self.incomingConnectionLabel.setFont(font)
        self.incomingConnectionLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.incomingConnectionLabel.setObjectName("incomingConnectionLabel")
        self.horizontalLayout_4.addWidget(self.incomingConnectionLabel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.acceptConnectionButton = QtWidgets.QPushButton(parent=self.mainPage)
        self.acceptConnectionButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.acceptConnectionButton.setObjectName("acceptConnectionButton")
        self.horizontalLayout_5.addWidget(self.acceptConnectionButton)
        self.declineConnectionButton = QtWidgets.QPushButton(parent=self.mainPage)
        self.declineConnectionButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.declineConnectionButton.setObjectName("declineConnectionButton")
        self.horizontalLayout_5.addWidget(self.declineConnectionButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_29.addLayout(self.verticalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_29.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_2.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_29.addWidget(self.line_2)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem8)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_66 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_66.setObjectName("horizontalLayout_66")
        self.connectButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectButton.sizePolicy().hasHeightForWidth())
        self.connectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.connectButton.setFont(font)
        self.connectButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_66.addWidget(self.connectButton)
        self.disconnectButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disconnectButton.sizePolicy().hasHeightForWidth())
        self.disconnectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.disconnectButton.setFont(font)
        self.disconnectButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.disconnectButton.setObjectName("disconnectButton")
        self.horizontalLayout_66.addWidget(self.disconnectButton)
        self.addContactButton = QtWidgets.QPushButton(parent=self.mainPage)
        self.addContactButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.addContactButton.setObjectName("addContactButton")
        self.horizontalLayout_66.addWidget(self.addContactButton)
        self.removeContactButton = QtWidgets.QPushButton(parent=self.mainPage)
        self.removeContactButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.removeContactButton.setObjectName("removeContactButton")
        self.horizontalLayout_66.addWidget(self.removeContactButton)
        self.connectingSpinnerLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectingSpinnerLabel.sizePolicy().hasHeightForWidth())
        self.connectingSpinnerLabel.setSizePolicy(sizePolicy)
        self.connectingSpinnerLabel.setText("")
        self.connectingSpinnerLabel.setScaledContents(True)
        self.connectingSpinnerLabel.setObjectName("connectingSpinnerLabel")
        self.horizontalLayout_66.addWidget(self.connectingSpinnerLabel)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_66.addItem(spacerItem9)
        self.verticalLayout_24.addLayout(self.horizontalLayout_66)
        self.contactTable = QtWidgets.QTableWidget(parent=self.mainPage)
        self.contactTable.setStyleSheet("color: white;\n"
"gridline-color: rgb(50, 50, 50);")
        self.contactTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.contactTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.contactTable.setObjectName("contactTable")
        self.contactTable.setColumnCount(4)
        self.contactTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.contactTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.contactTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.contactTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.contactTable.setHorizontalHeaderItem(3, item)
        self.contactTable.horizontalHeader().setVisible(True)
        self.contactTable.horizontalHeader().setCascadingSectionResizes(False)
        self.contactTable.horizontalHeader().setDefaultSectionSize(150)
        self.contactTable.horizontalHeader().setMinimumSectionSize(50)
        self.contactTable.horizontalHeader().setStretchLastSection(True)
        self.contactTable.verticalHeader().setVisible(False)
        self.contactTable.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_24.addWidget(self.contactTable)
        self.verticalLayout_29.addLayout(self.verticalLayout_24)
        self.line_11 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_11.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.line_11.setLineWidth(1)
        self.line_11.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_29.addWidget(self.line_11)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem10)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalLayout_74 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_74.setObjectName("horizontalLayout_74")
        self.selectedFileLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectedFileLabel.sizePolicy().hasHeightForWidth())
        self.selectedFileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.selectedFileLabel.setFont(font)
        self.selectedFileLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.selectedFileLabel.setObjectName("selectedFileLabel")
        self.horizontalLayout_74.addWidget(self.selectedFileLabel)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_74.addItem(spacerItem11)
        self.verticalLayout_28.addLayout(self.horizontalLayout_74)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.selectFileButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFileButton.sizePolicy().hasHeightForWidth())
        self.selectFileButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.selectFileButton.setFont(font)
        self.selectFileButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout_75.addWidget(self.selectFileButton)
        self.sendButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.sendButton.setFont(font)
        self.sendButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout_75.addWidget(self.sendButton)
        self.fileSentLabel = QtWidgets.QLabel(parent=self.mainPage)
        self.fileSentLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileSentLabel.sizePolicy().hasHeightForWidth())
        self.fileSentLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.fileSentLabel.setFont(font)
        self.fileSentLabel.setStyleSheet("color: #4CAF50;")
        self.fileSentLabel.setObjectName("fileSentLabel")
        self.horizontalLayout_75.addWidget(self.fileSentLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_75.addItem(spacerItem12)
        self.verticalLayout_28.addLayout(self.horizontalLayout_75)
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.sendProgressBar = QtWidgets.QProgressBar(parent=self.mainPage)
        self.sendProgressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendProgressBar.sizePolicy().hasHeightForWidth())
        self.sendProgressBar.setSizePolicy(sizePolicy)
        self.sendProgressBar.setMinimumSize(QtCore.QSize(190, 0))
        self.sendProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.sendProgressBar.setFont(font)
        self.sendProgressBar.setStyleSheet("QProgressBar {\n"
"    border-radius: 5px;\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    text-align: center;\n"
"    color: white\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    /* Progress Version */\n"
"    background-color: #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.sendProgressBar.setProperty("value", 0)
        self.sendProgressBar.setTextVisible(True)
        self.sendProgressBar.setInvertedAppearance(False)
        self.sendProgressBar.setObjectName("sendProgressBar")
        self.horizontalLayout_76.addWidget(self.sendProgressBar)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_76.addItem(spacerItem13)
        self.verticalLayout_28.addLayout(self.horizontalLayout_76)
        self.horizontalLayout_77 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_77.setObjectName("horizontalLayout_77")
        self.receiverDownloadedFileLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiverDownloadedFileLabel.sizePolicy().hasHeightForWidth())
        self.receiverDownloadedFileLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(10)
        font.setBold(True)
        self.receiverDownloadedFileLabel.setFont(font)
        self.receiverDownloadedFileLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.receiverDownloadedFileLabel.setObjectName("receiverDownloadedFileLabel")
        self.horizontalLayout_77.addWidget(self.receiverDownloadedFileLabel)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_77.addItem(spacerItem14)
        self.verticalLayout_28.addLayout(self.horizontalLayout_77)
        self.verticalLayout_29.addLayout(self.verticalLayout_28)
        self.line_12 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_12.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.line_12.setLineWidth(1)
        self.line_12.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_12.setObjectName("line_12")
        self.verticalLayout_29.addWidget(self.line_12)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem16)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.readyToReceiveLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readyToReceiveLabel.sizePolicy().hasHeightForWidth())
        self.readyToReceiveLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        font.setBold(True)
        self.readyToReceiveLabel.setFont(font)
        self.readyToReceiveLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.readyToReceiveLabel.setObjectName("readyToReceiveLabel")
        self.horizontalLayout_71.addWidget(self.readyToReceiveLabel)
        self.verticalLayout_27.addLayout(self.horizontalLayout_71)
        self.horizontalLayout_72 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_72.setObjectName("horizontalLayout_72")
        self.receiveButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveButton.sizePolicy().hasHeightForWidth())
        self.receiveButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.receiveButton.setFont(font)
        self.receiveButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.receiveButton.setObjectName("receiveButton")
        self.horizontalLayout_72.addWidget(self.receiveButton)
        self.rejectButton = QtWidgets.QPushButton(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rejectButton.sizePolicy().hasHeightForWidth())
        self.rejectButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.rejectButton.setFont(font)
        self.rejectButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    border-radius: 7px;\n"
"    color: white;\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgba(169, 169, 169, 0.7);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(105, 105, 105, 0.9);\n"
"}")
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout_72.addWidget(self.rejectButton)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_72.addItem(spacerItem17)
        self.verticalLayout_27.addLayout(self.horizontalLayout_72)
        self.horizontalLayout_73 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_73.setSpacing(6)
        self.horizontalLayout_73.setObjectName("horizontalLayout_73")
        self.receiveProgressBar = QtWidgets.QProgressBar(parent=self.mainPage)
        self.receiveProgressBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receiveProgressBar.sizePolicy().hasHeightForWidth())
        self.receiveProgressBar.setSizePolicy(sizePolicy)
        self.receiveProgressBar.setMinimumSize(QtCore.QSize(190, 0))
        self.receiveProgressBar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.receiveProgressBar.setFont(font)
        self.receiveProgressBar.setStyleSheet("QProgressBar {\n"
"    border-radius: 5px;\n"
"    background-color: rgba(169, 169, 169, 0.2);\n"
"    text-align: center;\n"
"    color: white\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    /* Progress Version */\n"
"    background-color: #4CAF50;\n"
"    border-radius: 5px;\n"
"}")
        self.receiveProgressBar.setProperty("value", 0)
        self.receiveProgressBar.setTextVisible(True)
        self.receiveProgressBar.setInvertedAppearance(False)
        self.receiveProgressBar.setObjectName("receiveProgressBar")
        self.horizontalLayout_73.addWidget(self.receiveProgressBar)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_73.addItem(spacerItem18)
        self.verticalLayout_27.addLayout(self.horizontalLayout_73)
        self.verticalLayout_29.addLayout(self.verticalLayout_27)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_29.addItem(spacerItem19)
        self.line_10 = QtWidgets.QFrame(parent=self.mainPage)
        self.line_10.setStyleSheet("background-color: rgb(50, 50, 50);")
        self.line_10.setLineWidth(1)
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.verticalLayout_29.addWidget(self.line_10)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.receivingLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.receivingLabel.sizePolicy().hasHeightForWidth())
        self.receivingLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(True)
        self.receivingLabel.setFont(font)
        self.receivingLabel.setStyleSheet("color: red;")
        self.receivingLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.receivingLabel.setObjectName("receivingLabel")
        self.verticalLayout_26.addWidget(self.receivingLabel)
        self.inboundConnectionLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inboundConnectionLabel.sizePolicy().hasHeightForWidth())
        self.inboundConnectionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(True)
        self.inboundConnectionLabel.setFont(font)
        self.inboundConnectionLabel.setStyleSheet("color: red;")
        self.inboundConnectionLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.inboundConnectionLabel.setObjectName("inboundConnectionLabel")
        self.verticalLayout_26.addWidget(self.inboundConnectionLabel)
        self.outboundConnectionLabel = QtWidgets.QLabel(parent=self.mainPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outboundConnectionLabel.sizePolicy().hasHeightForWidth())
        self.outboundConnectionLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(9)
        font.setBold(True)
        self.outboundConnectionLabel.setFont(font)
        self.outboundConnectionLabel.setStyleSheet("color: red;")
        self.outboundConnectionLabel.setObjectName("outboundConnectionLabel")
        self.verticalLayout_26.addWidget(self.outboundConnectionLabel)
        self.verticalLayout_29.addLayout(self.verticalLayout_26)
        self.stackedWidget.addWidget(self.mainPage)
        self.loadingPage = QtWidgets.QWidget()
        self.loadingPage.setObjectName("loadingPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.loadingPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem20)
        self.loadingSpinnerLabel = QtWidgets.QLabel(parent=self.loadingPage)
        self.loadingSpinnerLabel.setText("")
        self.loadingSpinnerLabel.setObjectName("loadingSpinnerLabel")
        self.verticalLayout_4.addWidget(self.loadingSpinnerLabel)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem21)
        self.stackedWidget.addWidget(self.loadingPage)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setBold(True)
        self.statusbar.setFont(font)
        self.statusbar.setStyleSheet("color: rgb(255, 255, 255);")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "P2P File Share"))
        self.ipLabel.setText(_translate("MainWindow", "Your IP address:"))
        self.fingerprintLabel.setText(_translate("MainWindow", "Your fingerprint:"))
        self.copyIPButton.setText(_translate("MainWindow", "Copy IP"))
        self.copyFingerprintButton.setText(_translate("MainWindow", "Copy Fingerprint"))
        self.usePortLabel.setText(_translate("MainWindow", "Port:"))
        self.enableReceivingButton.setText(_translate("MainWindow", "Enable Receiving"))
        self.disableReceivingButton.setText(_translate("MainWindow", "Disable Receiving"))
        self.incomingConnectionLabel.setText(_translate("MainWindow", "Incoming connection from:"))
        self.acceptConnectionButton.setText(_translate("MainWindow", "Accept"))
        self.declineConnectionButton.setText(_translate("MainWindow", "Decline"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.disconnectButton.setText(_translate("MainWindow", "Disconnect"))
        self.addContactButton.setText(_translate("MainWindow", "Add Contact"))
        self.removeContactButton.setText(_translate("MainWindow", "Remove Contact"))
        item = self.contactTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.contactTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "IP"))
        item = self.contactTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        item = self.contactTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Fingerprint"))
        self.selectedFileLabel.setText(_translate("MainWindow", "Selected file:"))
        self.selectFileButton.setText(_translate("MainWindow", "Select File"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.fileSentLabel.setText(_translate("MainWindow", "File sent"))
        self.receiverDownloadedFileLabel.setText(_translate("MainWindow", "The sent file has not yet been downloaded by the receiver"))
        self.readyToReceiveLabel.setText(_translate("MainWindow", "Ready to receive:"))
        self.receiveButton.setText(_translate("MainWindow", "Receive"))
        self.rejectButton.setText(_translate("MainWindow", "Reject"))
        self.receivingLabel.setText(_translate("MainWindow", "Receiving disabled"))
        self.inboundConnectionLabel.setText(_translate("MainWindow", "No inbound connection"))
        self.outboundConnectionLabel.setText(_translate("MainWindow", "No outbound connection"))
